Assignment4/Assignment4/Models/Sales.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Assignment4Entities : DbContext
    {
        public Assignment4Entities()
            : base("name=Assignment4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<saleinfo> saleinfoes { get; set; }
    }
}

Assignment4/Assignment4/Models/Sales.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Jasveer\Desktop\QA-Assignments\PROG8170_Assignment4\Assignment4\Assignment4\Models\Sales.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Assignment4/Assignment4/Models/Sales.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Assignment4/Assignment4/Models/saleinfo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saleinfo
    {
        public int id { get; set; }
        public string name { get; set; }
        public string contact_no { get; set; }
        public string contact_email { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string car_model { get; set; }
        public string car_make { get; set; }
        public string car_year { get; set; }
    }
}

Assignment4/Assignment4/Models/salesinfo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Assignment4.Models
{
    public class salesinfo
    {
        public int _id { get; set; }
        [DisplayName("Name")]
        public string _name { get; set; }
        [DisplayName("Contact number")]
        public string _contact_no { get; set; }
        [DisplayName("Contact Email")]
        public string _contact_email { get; set; }
        [DisplayName("Address")]
        public string _address { get; set; }
        [DisplayName("City")]
        public string _city { get; set; }
        [DisplayName("Car Model")]
        public string _car_model { get; set; }
        [DisplayName("Car Make")]
        public string _car_make { get; set; }
        [DisplayName("Car Year")]
        public string _car_year { get; set; }
    }
}

Assignment4/Assignment4/Controllers/SaleController.cs
using Assignment4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assignment4.Controllers
{
    public class SaleController : Controller
    {
        Assignment4Entities db;
        // GET: Sale
        public ActionResult Index()
        {

            db = new Assignment4Entities();

            var obj = (from s in db.saleinfoes
                       select new salesinfo
                       {
                           _name = s.name,
                           _contact_no = s.contact_no,
                           _contact_email = s.contact_email,
                           _address = s.address,
                           _city = s.city,
                           _car_make = s.car_make,
                           _car_model = s.car_model,
                           _car_year = s.car_year
                       }).ToList<salesinfo>();

            db.Dispose();
            return View(obj);
        }

        public ActionResult AddInfo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddInfo(salesinfo obj)
        {
            saleinfo oSel = new saleinfo()
            {
                name = obj._name,
                address = obj._address,
                city = obj._city,
                contact_email = obj._contact_email,
                contact_no = obj._contact_no,
                car_make = obj._car_make.Replace(" ", "-"),
                car_model = obj._car_model.Replace(" ", "-"),
                car_year = obj._car_year
            };

            db = new Assignment4Entities();
            db.saleinfoes.Add(oSel);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Assignment4/Assignment4/Views/Sale/AddInfo.cshtml
@model Assignment4.Models.salesinfo

@{
    ViewBag.Title = "Add Car";
}

<h2>Add Car</h2>
<style>
    .errorMessage{
        color:#ff0000;
    }
</style>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <div class="row">
            <div class="col-md-2 col-sm-2"></div>
            <div class="col-md-8 col-sm-8">
                <div class="row">
                    <div class="col-md-2 col-sm-2"></div>
                    <div class="col-md-8 col-sm-8"><label id="lblError" class="errorMessage"></label></div>
                    <div class="col-md-2 col-sm-2"></div>
                </div>
               
                <div class="form-group">
                    @Html.LabelFor(model => model._name, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model._name, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model._contact_no, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model._contact_no, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model._contact_email, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model._contact_email, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model._address, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model._address, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model._city, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model._city, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model._car_make, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model._car_make, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model._car_model, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model._car_model, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model._car_year, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model._car_year, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <input type="submit" value="Submit" id="btnSubmit" class="btn btn-primary" />
                        <a href="~/Sale/Index" class="btn btn-warning">Cancel </a>
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-sm-2"></div>
        </div>
    </div>
}


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script>
    $('#btnSubmit').click(function (e) {
        var isValid = true;
        debugger;
        //$('#lblError').html('<h3>Error Messages<h3/><hr />');
        if ($('input[name=_name]').val() == '') {
            isValid = false;
            $('#lblError').append('</br> Name is required');
        }
        if ($('input[name=_contact_email]').val() == '') {
            isValid = false;
            $('#lblError').append('</br>Contact email is required');
        }
        else {
            regex = /^([A-Za-z0-9_\-\.])+\@@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
            if (!regex.test($('input[name=_contact_email]').val())) {
                $('#lblError').append('</br>Invalid Contact Email');
                isValid = false;
            }
        }
        if ($('input[name=_contact_no]').val() == '') {
            isValid = false;
            $('#lblError').append('</br>Contact No is required');
        }
        else {
			regex = /^(?=.*[0-9])[- +()0-9]+$/;
            if ($('input[name=_contact_no]').val().length <= 15) {
				if (!regex.test($('input[name=_contact_no]').val()))
				{
                    isValid = false;
                    $('#lblError').append('</br>Invalid Contact No');
                }
            }
            else {
                isValid = false;
                $('#lblError').append('</br>Contact No length should be 10 digits');
            }
        }
        if ($('input[name=_address]').val() == '') {
            isValid = false;
            $('#lblError').append('</br>Address is required');
        }
        if ($('input[name=_city]').val() == '') {
            isValid = false;
            $('#lblError').append('</br>City is required');
        }
        if ($('input[name=_car_make]').val() == '') {
            isValid = false;
            $('#lblError').append('</br>Car make is required');
        }
        if ($('input[name=_car_model]').val() == '') {
            isValid = false;
            $('#lblError').append('</br>Car model is required');
        }
        if ($('input[name=_car_year]').val() == '') {
            isValid = false;
            $('#lblError').append('</br>Car year is required');
        }
        else {
            if ($.isNumeric($('input[name=_car_year]').val())) {
                $('#lblErrorCarYear').html('');
                if ($('input[name=_car_year]').val() * 1 < 2000 || $('input[name=_car_year]').val() * 1 > 2018) {
                    isValid = false;
                    $('#lblError').append('</br>Year selected should be between 1990 - 2018');
                }
            }
            else {
                isValid = false;
                $('#lblError').append('</br>Invalid car year selected');
            }
        }
        if (!isValid) {
            e.preventDefault();
            e.stopPropagation();
        }
    });

</script>

Assignment4/Assignment4/Views/Sale/Index.cshtml
@model IEnumerable<Assignment4.Models.salesinfo>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "AddInfo")
</p>
<table class="table">
    <tr> 
        <th>
            @Html.DisplayNameFor(model => model._name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model._contact_no)
        </th>
        <th>
            @Html.DisplayNameFor(model => model._contact_email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model._address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model._city)
        </th>
        <th>
            @Html.DisplayNameFor(model => model._car_make)
        </th>
        <th>
            @Html.DisplayNameFor(model => model._car_model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model._car_year)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr> 
        <td>
            @Html.DisplayFor(modelItem => item._name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item._contact_no)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item._contact_email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item._address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item._city)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item._car_make)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item._car_model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item._car_year)
        </td>
        <td>
           <a href="http://www.jdpower.com/cars/@item._car_make/@item._car_model/@item._car_year" target="_blank">Click To View</a>
        </td>
    </tr>
}

</table>

Assignment4/Assignment4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Conestoga</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("JD Power", "Index", "Sale", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Conestoga</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>